### ISSUE TITLE
PDF accessibility

### ISSUE THREAD

**Issue by dapperjapper** [mbutterick/typesetting#15]
I know this project is in it's early stages and I don't want to seem ungrateful for the open source contributions you've brought to the typography community, but I wanted to make sure this is on your radar for this project. 

PDFs have a specification that allows them to annotate semantic structure ('tags') on top of whatever visual stuff they contain. This runs parallel to PDF bookmarks, which are helpful for jumping around the table of contents, but tags have even lower-level structure. (I don't know much about the technical stuff so correct me if I'm wrong.)

PDF tags make PDFs readable for screen readers, and are required within certain institutions that have rules around accessibility and equitable access. (For example, in the US Federal agencies must be "508 compliant.")

Word (and probably some other typesetting tools) generate tagged PDFs, but [LaTeX has never really been able to do this.](https://twitter.com/jasperclarkberg/status/1038865653581709312) I think it would be an amazing contribution to the state of accessibility in academia if  there were a typesetting tool that *did* generate tagged PDFs.

I am interested in helping with this, but I'm not sure if this project is in a state that's ready for collaboration yet. Also, I have experience in high-level programming languages but I would probably have to do some reading on PDF compilers.

**Comment by mbutterick** [comment]
Most of my PDF-making code was ported from the `pdfkit` project a few years ago. In the past year, `pdfkit` has added support for Tagged PDF. So the most likely path to supporting Tagged PDF is to go back to `pdfkit` and port this new code into `quad` (or more specifically `pitfall`, which is the PDF-generating part of the library)
